language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - pecl install imagick
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make test
