sudo: false

notifications:
  email: false
  
cache:
  directories:
    - $HOME/.composer/cache/files
    
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly
    - php: hhvm



before_script:
  - composer selfupdate
  - composer update --prefer-dist --no-interaction
  

script: make test
