language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install --ignore-platform-reqs

script: vendor/bin/phpunit
