name: PHP Tests

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        operating-system: [ubuntu-22.04]
        php-versions: ['7.3', '7.4', '8.0', '8.1']
      fail-fast: false
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test
